### ISSUE TITLE
[suggestion] bed file of TSRs.

### ISSUE THREAD

**Issue by rpolicastro** [BrendelGroup/TSRchitect#171]
The generated list of TSRs already has the information required to output a bed file for TSR visualization and downstream analysis (such as motif finding). It would be handy to have a function to generate it for you, instead of having to do it by hand every time. You could also perhaps include the score column to shade TSR "strength" in a genome viewer, such as scaling nTAGs between 0-1000.

I've included an example from the list of TSRs Taylor generated for the latest STRIPE-seq run.
[TSRs_scored.bed.zip](https://github.com/BrendelGroup/TSRchitect/files/2133591/TSRs_scored.bed.zip)

**Comment by vpbrendel** [comment]
This issues has been addressed.  writeTSR can now put out either bed or gff output, with the score scaled to be between 0 and 1000 as follows:

m <- median(tsr.df$nTAGs)
tsr.df$score <- round(100*pmin(tsr.df$nTAGs/m,10),0)
