### ISSUE TITLE
[suggestion] Sample sheet to input experiment information.

### ISSUE THREAD

**Issue by rpolicastro** [BrendelGroup/TSRchitect#172]
At the moment information about the experiments are input manually into loadTSSobj. This can be somewhat inconvenient if you are processing a large number of files. Also, as stated in the documentation, you need to be careful to match the order with the bam files.

A few packages let you upload sample information from a separate tab delimited file or data.frame object. This ensures that sample information matches with the associated bam file, and that its convenient to process a large number of files at the same time.

A good example of this is the [DiffBind](https://bioconductor.org/packages/release/bioc/html/DiffBind.html) package.

**Comment by vpbrendel** [comment]
The latest update to TSRchitect (githhub site only, not Bioconductor as yet) takes care of this excellent suggestion. It is now possible to call loadTSSobj() with parameter "sampleSheet=<ssfile>" where ssfile is a tab-delimited 3-column spreadsheet (or an Excel spreadsheet with information on Sheet1 of a workbook); column headers should be "SAMPLE", "ReplicateID", and "FILE", respectively, and in the following rows you can specify sample names, replicate sample numbers, and bam and/or bed files to be processed, providing the same information as previously in arguments to the loadTSSobj() function.  See the vignette Rmd for a brief description.
