### ISSUE TITLE
[suggestion] bedgraph file for TSSs

### ISSUE THREAD

**Issue by rpolicastro** [BrendelGroup/TSRchitect#173]
After filtering, TSRchitect provides you a list of TSSs and the number of tags for each position. It would be great to have a convenience function that can turn this information into a bedgraph for visualization in a genome viewer. It should perhaps output a separate bedgraph for both the + and - strand. I've attached example files below from the latest STRIPE-seq run with yeast.

[TSS_bedgraphs.zip](https://github.com/BrendelGroup/TSRchitect/files/2133646/TSS_bedgraphs.zip)

**Comment by vpbrendel** [comment]
This issue has been addressed with the addition of writeTSS which allows output of TSS counts in bedGraph format. Note that - strand positions are given negative TAG counts, and in positions that have tags on both strands, only the highest in absolute value is shown (a rare event, but a necessary convention to give proper bedGraph format).
