### ISSUE TITLE
[suggestion] Add outputDir argument to processTSS and determineTSR

### ISSUE THREAD

**Issue by rpolicastro** [BrendelGroup/TSRchitect#201]
Would be handy to have an explicit argument, such as `outputDir`, to specify where you want the text files to be written if `writeTable = TRUE` in either `processTSS` or `determineTSR`. It's often a little more convenient than having to change the working directory for each of the commands.

**Comment by vpbrendel** [comment]
I don't know why one would want to change the working directory for each of the commands - that seems to be a very non-R kind of way.  All calculations should be done within R on the S4 object, with output to disk an option when needed.

**Comment by rpolicastro** [comment]
Hi Volker,

Currently when `writeTable = TRUE`, the text files containing the TSSs and TSRs are written to the current working directory. What this means is if you wanted to write the TSSs to a directory other than the current working directory, you need to change directories to the new directory before running the command in R, or move the files after creation. I was suggesting adding an explicit `outputDir` argument so that instead of having to change directories or move the files, you can specify where you want them to be output to.

**Comment by vpbrendel** [comment]
Understood, but again I don't think any of that is necessary.  More straightforward would be to move files from the working directory after R is finished, if necessary.
