### ISSUE TITLE
mergeSampleData behavior and speed for TSSs

### ISSUE THREAD

**Issue by rpolicastro** [BrendelGroup/TSRchitect#227]
mergeSampleData seems to take a long time to run, and for TSSs it appears to not add TSSs that are overlapping.

The speed of this for TSS merging could be greatly increased, as well as the behavior being more of what is expected, by using the dplyr library.

```
merged <- rbind(sample.1, sample.2) %>%
   group_by(seq, TSS, strand) %>%
   summarize(nTAGs = sum(nTAGs)) %>%
   arrange(seq, TSS) %>%
   as.data.frame()
```

Where sample.1 and sample.2 are two hypothetical data frames stored in the @tssCountData slot. This will output a data frame that is position sorted, and where any overlapping TSSs are summed. It should only take a few seconds to run as well.

**Comment by vpbrendel** [comment]
Well, the current version of mergeSampleData is definitely adding the TSSs in the same position. If you find this not to be the case, I definitely need to see the example.
As to speed, the dplyr approach would have the same algorithmic steps involving initially the sorting (grouping). That would be impossible to accomplish in a few seconds on large data sets.
Thus, I think we need a good test case to see whether your elegant dplyr approach can match or better the current implementation.

**Comment by rpolicastro** [comment]
I'll send the data to you over email. This is what I found for the data using TSRchitect v1.8.9.

```
> time.1 <- Sys.time(); merged <- mergeSampleData(stripe); time.2 <- Sys.time()
> time.2 - time.1
Time difference of 9.302535 mins
```

There are two replicate groups in the data. When you look at the merged TSSs for the first replicate group it appears that overlapping TSSs were not summed.

```
> merged@tssCountDataMerged[[1]] %>% group_by(seq, TSS, strand) %>% filter(n() > 1) %>% arrange(seq, TSS)
# A tibble: 611,357 x 4
# Groups:   seq, TSS, strand [251,415]
   seq     TSS strand nTAGs
   <chr> <dbl> <chr>  <dbl>
 1 I      2485 +          1
 2 I      2485 +          1
 3 I      5894 -          1
 4 I      5894 -          1
 5 I      6331 -          1
 6 I      6331 -          1
 7 I      6331 -          3
 8 I      6336 -          1
 9 I      6336 -          1
10 I      6342 -          2
# ... with 611,347 more rows
```

This would be the equivalent using dplyr.

```
time.1 <- Sys.time();
merged.1 <- rbind(stripe@tssCountData[[1]], stripe@tssCountData[[2]], stripe@tssCountData[[3]]) %>%
group_by(seq, TSS, strand) %>%
summarize(nTAGs=sum(nTAGs)) %>%
arrange(seq, TSS) %>%
as.data.frame();
merged.2 <- rbind(stripe@tssCountData[[4]], stripe@tssCountData[[5]], stripe@tssCountData[[6]]) %>%
group_by(seq, TSS, strand) %>%
summarize(nTAGs=sum(nTAGs)) %>%
arrange(seq, TSS) %>%
as.data.frame();
merged.3 <- rbind(stripe@tssCountData[[1]], stripe@tssCountData[[2]], stripe@tssCountData[[3]], stripe@tssCountData[[4]], stripe@tssCountData[[5]], stripe@tssCountData[[6]]) %>%
group_by(seq, TSS, strand) %>%
summarize(nTAGs=sum(nTAGs)) %>%
arrange(seq, TSS) %>%
as.data.frame();
time.2 <- Sys.time()
```
```
> time.2 - time.1
Time difference of 12.62871 secs
```
This time it only took 12 seconds, instead of 9 minutes.

```
> merged.1 %>% group_by(seq, TSS, strand) %>% filter(n() > 1) %>% arrange(seq, TSS)
# A tibble: 0 x 4
# Groups:   seq, TSS, strand [0]
# ... with 4 variables: seq <chr>, TSS <dbl>, strand <chr>, nTAGs <dbl>
```
It appears that the overlapping TSSs were properly summed as well.

Just to confirm, here is a TSS that was duplicated in the TSRchitect merge from above.

```
> merged.1 %>% filter(seq == "I" & TSS == 2485 & strand == "+")
  seq  TSS strand nTAGs
1   I 2485      +     2
```

**Comment by vpbrendel** [comment]
The most recent accepted pull request should close this issue to our satisfaction.  Great suggestion, Bob!
