### ISSUE TITLE
Demo produces unexpected number of slots in @tssCountDataMerged and @tsrDataMerged

### ISSUE THREAD

**Issue by rtraborn** [BrendelGroup/TSRchitect#57]
After testing demo-RAMPAGEp.R on the most recent codebase using the IRBB7 data, I found that the resulting tssExperiment object contains 3 (instead of the expected 2) slots in @tssCountDataMerged and @tsrDataMerged.  I have not isolated the error yet, but am checking mergeSampleData.R first.

**Comment by vpbrendel** [comment]
Well, this is documented in the code:  slot "samples+1" is reserved for the merged data from ALL samples.
All perfectly fine.
Volker

**Comment by rtraborn** [comment]
@vpbrendel Ok. I strongly suggest we assign these data into a 'tssDataAll' (for example) slot on the tssExperiment object. This (rather than the current nexperiments+1) is consistent with the way we've handled the rest of the data.

**Comment by rtraborn** [comment]
Per @vpbrendel and my conversation yesterday, I'm going to close this issue for now. We will consider a distinct slot at a later date if necessary.
